version: 0.0
os: linux

files:
  - source: /
    destination: /opt/nextflow
    overwrite: true
file_exists_behavior: OVERWRITE

permissions:
      - object: /opt/nextflow
        pattern: '**'
        owner: ec2-user
        group: ec2-user

#hooks:
#  BeforeInstall:
#    - location: ./scripts/install_dependencies.sh
#      timeout: 300
#      runas: root
#
#  AfterInstall:
#    - location: ./scripts/run_nextflow.sh
#      timeout: 300
#      runas: ec2-user
