version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t 992382809252.dkr.ecr.us-east-1.amazonaws.com/nextflow:$CODEBUILD_BUILD_NUMBER .
      - docker push 992382809252.dkr.ecr.us-east-1.amazonaws.com/nextflow:$CODEBUILD_BUILD_NUMBER
