name: Batch CodeDeploy CI

on:
  workflow_dispatch:

permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout

jobs:
  build:
    name: Run Code Deploy Job
    runs-on: ubuntu-latest
    environment: 'prod'     
 
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::992382809252:role/GithubOpenId
        role-session-name: githubActionSession
        aws-region: us-east-1
 
    - name: Create zip archive
      run: |
        zip -r  source.zip  . -x '*. git*'
      working-directory: ${{ github.workspace }}
 
    - name: Copy zip to S3
      run: aws s3 cp source.zip s3://pipeline-artifact-992382809252-us-east-2/
      env:
        AWS_DEFAULT_REGION: us-east-2
   
      
    - name: Tag Docker Image to Latest
      run: docker tag ${{ vars.REPO_NAME }}:latest public.ecr.aws/openscpca/${{ vars.REPO_NAME }}:latest
      
    - name: Push Docker Image to ECR
      run: docker push public.ecr.aws/openscpca/${{ vars.REPO_NAME }}:latest
